runtime: python
runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "3.11.3"
entrypoint: 'gunicorn -b :$PORT app:app'

env: flex

resources:
  cpu: 2
  disk_size_gb: 20
  memory_gb: 8

automatic_scaling:
  target_concurrent_requests: 100
