runtime: python
runtime_config:
  python_version: 3
entrypoint: 'gunicorn -b :$PORT app:app'

env: flex

resources:
  cpu: 2
  disk_size_gb: 20
  memory_gb: 8

automatic_scaling:
  target_concurrent_requests: 100
